Add friends and likes
PavelDubovik/java-filmorate pull request #3
Opened 2022-09-21 15:48 UTC by PavelDubovik

2022-09-22 12:36 UTC, andrew-larkin requested changes
Привет! Отличная работа, код написан очень качественно. Остается немного отрефакторить и будем готовы интегрироваться с БД

2022-09-22 12:36 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmStorage filmStorage, FilmService filmService) {
чтобы не создавать конструктор в контроллере, можно использовать ломбоковскую @RequiredArgsConstructor над классом

2022-09-22 12:36 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage filmStorage;
данную зависимость нужно внедрять только в сервис

2022-09-22 12:36 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmStorage.addFilm(film);
все запросы из контроллера только через сервис

2022-09-22 12:36 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (count < 0) {
лучше абсолютно все условия и какой-то дополнительный функционал перенести в сервис. в контроллере должен быть просто метод, вызывающий метод сервиса (без какой-то дополнительной логики)

2022-09-22 12:36 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>  public class UserController {
все замечания из FilmController актуальны и для этого контроллера

2022-09-27 10:51 UTC, avfyodorov reviewed
Добрый день!
Работа очень хорошая,  осталась всего пара косметических замечаний.

2022-09-27 10:51 UTC, avfyodorov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>  @Slf4j
то же самое

2022-09-27 10:51 UTC, avfyodorov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public Film addFilm(Film film) {
Суффиксы (Фильм, Пользователь) в названии методов можно спокойно убрать. И так понятно к какому типу объекта относится метод.

2022-09-27 10:51 UTC, avfyodorov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        userStorage.getUserById(userIdFirst);
Здесь методы вызываются по несколько раз подряд с одними и теми же аргументами. Может быть имеет смысл провести небольшой рефакторинг? Завести локальные переменные, например. 
На ваше усмотрение.

2022-09-27 17:15 UTC, PavelDubovik commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  @Slf4j
Не совсем понимаю какую библиотеку нужно отключить. List из util не могу отключить, т.к. использую интерфейс List когдаполучаю список популярных фильмов. Valid из validation тоже используется при валидации параметров методов.

2022-09-27 17:17 UTC, PavelDubovik commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>  @Slf4j
Здесь единственная библиотека List. Она мне нужна для методов получения всех пользователей, друзей пользователя и общих друзей пользователей.

2022-09-27 17:24 UTC, PavelDubovik commented
Приветствую! Спасибо за ревью! Скорректировал за исключением библеотек, т.к. не совсем понял, что требуется.

2022-09-28 10:21 UTC, avfyodorov reviewed
Добрый день!

Замечаний нет.
Работа принята.

2022-09-28 14:10 UTC, merged